### ISSUE TITLE
マークダウン形式でのコピー

### ISSUE THREAD

**Issue by yousan** [takedajs/TitleUrlCopy_Chrome#4]
すごく便利で助かっています 👍 

技術系の記事を書く際の文献の引用していてマークダウン方式で書いています。
オプションにマークダウンを追加してもらえないでしょうか？

```
[Example Page](https://example.com "Example Page")
```

**Comment by takedajs** [comment]
@yousan 
返信遅れてしまいすみません！
プルリクありがとうございます。動作確認が出来ましたらマージします😁

**Comment by yousan** [comment]
@takedajs コードを参考に追記させてもらいました！
よろしくおねがいします〜！

**Comment by takedajs** [comment]
@yousan アドオンを更新しました！
issue＆プルリクありがとうございました( ´ ▽ ` )ﾉ

https://chrome.google.com/webstore/detail/titleurlcopy/njopknnjcnnjcabniccieedkcpaabbpk?hl=ja&gl=JP

**Comment by yousan** [comment]
こちらこそありがとうございます！今後も応援しています！
